default = {
    "Label": {"Alignment": "Left",
              "Bold": False,
              "Italic": False,
              "MaxWidth": 100,
              "IconSize": 12},
    "InputItem": {"Type": "None",
                  "Location": "Right",
                  "Alignment": "Fill",
                  "HideOnExpand": False},
    "ExpandButton": {"Size": 12,
                     "Border": False},
    "Description": {"Text": False,
                    "Hover": True,
                    "MaxWidth": 200},
    "Body": {"Widget": "Container",
             "Args": False,
             "Expanded": False,
             "AlwaysExpanded": False,
             "ExpandOnValue": False,
             "Indent": 10},
    "Settings": {"Padding": [0, 0, 0, 0],
                 "AllowLock": True}}
