templates = {
    "int": {"InputItem": {"Type": "int"},
            "Body": False},
    "float": {"InputItem": {"Type": "float"},
              "Body": False},
    "bool": {"InputItem": {"Type": "bool"},
             "Body": {"ExpandOnValue": True}},
    "Group": {"Label": {"Bold": True},
              "InputItem": False,
              "Body": {"Widget": "Container"},
              "Settings": {"AllowLock": False}},
    "Choice": {"InputItem": {"Type": "Choice",
                             "Location": "Right",
                             "Alignment": "Center"},
               "Body": {"Widget": "Stack",
                        "Expanded": True}},
    "str": {"InputItem": {"Type": "strText"},
            "Body": False},
    "date": {"InputItem": {"Type": "date"},
             "Body": False},
    "dateTime": {"InputItem": {"Type": "dateTime"},
                 "Body": False},
    "time": {"InputItem": {"Type": "time"},
             "Body": False},
    "dict": {"InputItem": {"Type": "dict"},
             "Body": False},
    "list": {"InputItem": {"Type": "list"},
             "Body": False},
    "dictBuilder": {"InputItem": False,
                    "Label": {"Bold": True},
                    "Body": {"Widget": "dictBuilder",
                             "Expanded": True}},
    "listBuilder": {"InputItem": False,
                    "Label": {"Bold": True},
                    "Body": {"Widget": "listBuilder",
                             "Expanded": True}},
    "color": {"InputItem": False,
              "Body": {"Widget": "colorPicker",
                       "Expanded": True,
                       "Indent": 0}},
    "intS": {"InputItem": {"Type": "int"},
             "Body": {"Widget": "intSlider",
                      "Expanded": True,
                      "Indent": 0}},
    "floatS": {"InputItem": {"Type": "float"},
               "Body": {"Widget": "floatSlider",
                        "Expanded": True,
                        "Indent": 0}},
    "frame": {"InputItem": False,
              "Body": {"Widget": "frame",
                       "Expanded": True}}
}
