test_definition = {
    "Standard Inputs": {
        "Numeric": {
            "Num Standard": {"Type": "Group",
                             "Body": {"Expanded": True}},
            "Num Settings": {"Type": "Group",
                             "Body": {"Expanded": True}},
            "Num Advanced": {"Type": "Group",
                             "Body": {"Expanded": True}},
            "Int": {"Type": "int", "Group": "Num Standard"},
            "Int with range": {"Type": "int", "Group": "Num Settings",
                               "InputItem": {"Range": [0, 8]}},
            "Float": {"Type": "float", "Group": "Num Standard"},
            "Float 1 decimal": {"Type": "float", "Group": "Num Settings",
                                "InputItem": {"Decimals": 1}},
            "Float range/decimal": {"Type": "float", "Group": "Num Settings",
                                    "InputItem": {"Range": [0, 0.0001],
                                                  "Decimals": 5}},
            "Int with slider": {"Type": "intS", "Group": "Num Advanced"},
            "Float with slider": {"Type": "floatS", "Group": "Num Advanced"},
        },
        "String": {
            "Str Standard": {"Type": "Group",
                             "Body": {"Expanded": True}},
            "Line input": {"Type": "str", "Group": "Str Standard",
                           "InputItem": {"Type": "strLine"}},
            "Text input": {"Type": "str", "Group": "Str Standard"}
        },
        "Other": {
            "Primitives": {"Type": "Group",
                           "Body": {"Expanded": True}},
            "Misc": {"Type": "Group",
                     "Body": {"Expanded": True}},
            "Boolean": {"Type": "bool", "Group": "Primitives"},
            "Dictionary": {"Type": "dict", "Group": "Primitives"},
            "List": {"Type": "list", "Group": "Primitives"},
            "Choice": {"Type": "Choice", "Group": "Misc",
                       "Options": ["Option 1", "Option 2", "Option 3"],
                       "Body": False},
            "Time": {"Type": "time", "Group": "Misc"},
            "Date": {"Type": "date", "Group": "Misc"},
            "DateTime": {"Type": "dateTime", "Group": "Misc"},
            "Color": {"Type": "color", "Group": "Misc",
                      "Body": {"AlwaysExpanded": True}}
        },
    },
    "Advanced": {
        "Grouping": {
            "Normal Group": {"Type": "Group",
                             "Description": {"Text": "This will start closed"}},
            "test1": {"Type": "int", "Group": "Normal Group"},
            "test2": {"Type": "str", "Group": "Normal Group"},
            "Extended Group": {"Type": "Group",
                               "Description": {"Text": "This will start opened"},
                               "Body": {"Expanded": True}},
            "test3": {"Type": "int", "Group": "Extended Group"},
            "test4": {"Type": "str", "Group": "Extended Group"},
            "Bool SubSetting": {"Type": "bool",
                                "Description": {"Text": "This extends based on value"}},
            "test5": {"Type": "int", "SubSetting": "Bool SubSetting"},
            "test6": {"Type": "str", "SubSetting": "Bool SubSetting"},
            "Choice SubSetting": {"Type": "Choice",
                                  "Options": ["Int settings", "Float settings"]},
            "test7": {"Type": "int", "SubSetting": {"Choice SubSetting": "Int settings"}},
            "test8": {"Type": "int", "SubSetting": {"Choice SubSetting": "Int settings"}},
            "test9": {"Type": "float", "SubSetting": {"Choice SubSetting": "Float settings"}},
        },
        "Builder": {
            "Build_helpers": {"Type": "Group", "Body": {"Expanded": True}},
            "Dict Builder": {"Type": "dictBuilder",
                             "Group": "Build_helpers",
                             "Body": {"Args": {"Direction": {"Type": "Choice",
                                                             "Options": ["Up", "Right", "Down", "Left"],
                                                             "Body": False},
                                               "Steps": {"Type": "int"}}}},
            "List Builder": {"Type": "listBuilder", "Group": "Build_helpers"}
        }
    }
}

user_defined = {"Data Stream 1": {"hello": {"Type": "int", "Group": "hello8"},
                                  "Guess": {"Type": "Group", "Description": {
                                      "Text": "This is a group description",
                                      "Hover": True
                                  }},
                                  "Who": {"Type": "Group", "Group": "Guess"},
                                  "Has": {"Type": "Group", "Group": "Who"},
                                  "Nested Groups": {"Type": "Group", "Group": "Has"},
                                  "hello1": {"Type": "int", "Group": "Nested Groups"},
                                  "hello2": {"Type": "int", "Group": "Nested Groups"},
                                  "hello3": {"Type": "str", "Group": "Has"},
                                  "hello8": {"Type": "intS"},
                                  "hello5": {"Type": "int", "SubSetting": "hello4"},
                                  "Something": {"Type": "dictBuilder",
                                                "Body": {"Args": {"1": {"Type": "int"},
                                                                  "2": {"Type": "str"}}}}},
                "Data Stream 2": {"hello4": {"Type": "bool", "Tab": "shit"},
                                  "hello6": {"Type": "int", "Tab": "shit"},
                                  "hello7": {"Type": "Choice", "Options": ["int", "float", "str"],
                                             "Tab": "settings"},
                                  "some int": {"Type": "int", "SubSetting": {"hello7": "int"}},
                                  "some float": {"Type": "float", "SubSetting": {"hello7": "float"}},
                                  "some str": {"Type": "str", "SubSetting": {"hello7": "str"}},
                                  "some str2": {"Type": "str", "SubSetting": {"hello7": "str"}},
                                  "some str3": {"Type": "str", "Tab": "settings"}
                                  }}
